title: "Dr. Sailesh K S"
description: "Assistant Professor (Sr.) | Mechanical Engineering | Nanofuels | Biofuels | Structural Mechanics"
author: "Sailesh K S"

theme: minima

header_pages:
  - index.md
  - about.md
  - publications.md
  - projects.md
  - contact.md

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional (edit if needed)
# baseurl: "/your-repo-name"
# url: "https://your-username.github.io"
